from datetime import datetime

def generate_report(
    finding,
    confidence,
    risk,
    region,
    stay
):

    report = f"""
🏥 AI MEDICAL REPORT
=================================

Generated On:
{datetime.now().strftime("%d-%m-%Y %H:%M:%S")}

MRI DIAGNOSIS
=================================

Finding:
{finding}

Confidence:
{confidence}%

Risk Level:
{risk}

Affected Region:
{region}

PATIENT RISK ANALYSIS
=================================

Predicted Hospital Stay:
{stay} Days

RECOMMENDATIONS
=================================

• Follow Medical Consultation

• Regular Monitoring Recommended

• Follow-up MRI Scan Suggested

• Clinical Evaluation Required

=================================
Generated By:
Synthetic Healthcare Intelligence Platform
"""

    return report